### PR TITLE
Reset namespace, conflicts with zk v1.9.6

### PR DESCRIPTION
**Pull request by lukaszx0**
Fixes compatibility with the latest zk gem version

/cc @slyphon @eric

### CODE REVIEW

**Comment by eric** [comment]
Ouch. Thanks for finding that.

**Comment by lukaszx0** [comment]
@eric Can we cut a patch release including this fix?

**Comment by slyphon** [comment]
yeah, i'll make a note to release later today or tomorrow

**Comment by lukaszx0** [comment]
@slyphon friendly reminder :)

**Comment by slyphon** [comment]
hey @lukaszx0, I just pushed 1.1.8 of zk-server, but to be totally honest, it's been a *while* since i've pushed the zk-server gem. If you could test it out for me and lemme know if it's ok, i'd greatly appreciate it :)

**Pull request merged**
